### ISSUE TITLE
Lack of Django > 3.0 compatibility

### ISSUE THREAD

**Issue by silv3rmat** [ad-m/django-teryt-tree#7]
Application cannot load, please see the relevant part of error traceback: 
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'

Per release notes, django.utils.encoding.python_2_unicode_compatible() was removed in Django3.0.

**Comment by ad-m** [comment]
Ja bym przyjął, że porzucamy wsparcie dla Python 2.7 w kolejnym wydaniu, bo osiągnął EOL ( https://endoflife.date/python ). Wówczas takie rzeczy nie są konieczne i można posprzątać kod. Oprócz poprawienia importów należy sprawdzić czy m. in. nie ma odwołań do ```six```, ```django.contrib.six``` i można zaktualizować składnie poprzez ```pyupgrade```.

**Comment by ad-m** [comment]
> Following the release of Django 3.0, we suggest that third-party app authors drop support for all versions of Django prior to 2.2. At that time, you should be able to run your package’s tests using python -Wd so that deprecation warnings appear. After making the deprecation warning fixes, your app should be compatible with Django 3.0.

https://docs.djangoproject.com/en/3.0/releases/3.0/

**Comment by ad-m** [comment]
Fixed in #8
